### ISSUE TITLE
Issue when detecting sensors

### ISSUE THREAD

**Issue by heaveaxy** [IvanBayan/Zabbix-lm-sensors-lld#2]
Testing on CentOS 7 with latest updates, I found that sensors detection works incorrectly:
```
	"data":[
		{"{#CHIP}":"coretemp-isa-0000", "{#SENSOR}":"temp1 temp2 temp3 temp4 temp5", "{#UNITS}":"°C"},
		{"{#CHIP}":"acpitz-virtual-0", "{#SENSOR}":"temp1 temp2", "{#UNITS}":"°C"}
	]
}
```

All sensor names puts in single sensor line.
One possible solution that make it work is to quote sensor query in discovery.sensor script like this:
`done <<< "$($SENSORS -u $chip 2>/dev/null|$EGREP "_input:"|$TR -d " "|$CUT -d_ -f1)"`
It works for me fine.

**Comment by IvanBayan** [comment]
Thank you, for your report. I've fixed it in commit 5d38653be4e8f520a2506020fc0821684e09bb8d
